config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :path => '',
    :path_name => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
    :cmontrollers => {:omniauth_callbacks => 'omniauth_callbacks',
                    :registrations => 'registrations'}

  root "pages#home"

  resources :products do
  	resources :orders, only: [ :create]
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :orders, only: [ :show ]

  get "my_products" => "products#my_products"

  get "my_purchases" => "pages#my_purchases"
  get "my_sales" => "pages#my_sales"

  resources :charges, only: [ :create ]

  get "search" => "pages#search"

  resources :contacts, only: [ :new, :create ]

end

app/models/contact.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class Contact < ActiveRecord::Base

	validates :name, presence: true
	validates :email, presence: true, email: true

	validates :body, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  before_save :set_order_price

  private
  	def set_order_price
  		if self.quantity != nil && self.price != nil 
  			self.total_price = (self.quantity * self.price).round(2)
  		end
  	end

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates :name, presence: true
	validates :description, presence: true
	validates :price, presence: true
	validates_numericality_of :price

	belongs_to :user
	has_many :orders
	has_many :reviews

	self.per_page = 3

	def short_description
		description.length > 130 ? description[0..130] + "..." : description
	end

	def self.search(search_text)
		where('name LIKE ? or description LIKE ?', "%#{search_text}%", "%#{search_text}%")
	end

	def has_reviews(user)
		reviews.map(&:user).include?(user)
	end

	def review_average
		reviews.average(:star)
	end


end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :products
  has_many :orders
  has_many :reviews       

  def full_name
  	first_name + " " + last_name
  end

  def self.from_facebook(auth)
  	user = User.where(email: auth.info.email).first

  	if user
  		return user
  	else
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  			user.provider = auth.prvider
  			user.uid = auth.provider
  			user.email = auth.info.email
  			user.password = Devise.friendly_token[0,20]
  			user.first_name = auth.info.first_name
  			user.last_name = auth.info.last_name
  			user.description = auth.info.description
  		end
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => params[:total_price],
	    :description => params[:description],
	    :currency    => 'usd'
	  )

	  product = Product.find(params[:product_id])

	  order = Order.create(
	  	user: current_user,
	  	product: product,
	  	price: params[:price],
	  	total_price: params[:total_price],
	  	quantity: params[:quantity],
	  	stripe_customer_id: customer.id,
	  	stripe_email: params[:stripeEmail],
	  	currency: charge.currency,
	  	description: charge.description
	  )

	  redirect_to products_path

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create

		@contact = Contact.create(contact_params)

		if @contact.save

			@name = params[:contact][:name]
			@email = params[:contact][:email]
			@body = params[:contact][:body]

			ContactMailer.contact_email(@name, @email, @body).deliver
			
			flash[:notice] = "Message sent successfully"
			redirect_to root_path
		else
			flash[:notice] = "Could not be saved !"
			render "new"
		end

	end

	private
		def contact_params
			params.require(:contact).permit(:name, :email, :body)
		end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
		@user = User.from_facebook(request.env['omniauth.auth'])

		if @user.persisted?
			sign_in_and_redirect @user, :event => 'auathentication'
			set_flash_message(:notice, :success, :kind => 'facebook') if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to_new_user_registration_url
		end
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def create
		@order = current_user.orders.create(order_params)
		if @order.save
			flash[:notice] = "Order created successfully"
			redirect_to @order.product
		end
	end

	private

		def order_params
			params.require(:order).permit(:user_id, :product_id, :quantity, :price, :total_price)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def my_purchases
  	@purchases = current_user.orders.order("created_at DESC")
  end

  def my_sales
  	@sales = current_user.products
  end

  def search
  	@products = Product.search(params[:q])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :new, :create, :update, :destroy ]

  def index
    @products = Product.paginate(:page => params[:page]).all.order("created_at DESC")
    
  end

  def new
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.create(product_params)
    
    if @product.save
      flash[:notice] = "Saved successfully"
      redirect_to @product
    else
      render "new"
    end
  end

  def show
    @reviews = @product.reviews
  end

  def edit

  end

  def update
    if @product.update(product_params)
      flash[:notice] = "Updated successfully"
      redirect_to products_path
    else
      render "edit"
    end
  end

  def destroy
    @product.delete
    flash[:notice] = "Deleted successfully"
    redirect_to products_path
  end

  def my_products
    @products = current_user.products.order("created_at DESC")
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end

    def find_product
      @product = Product.find(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def new
		super
	end

	def create
		super
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index

	end

	def create
		@review = current_user.reviews.create(review_params)

		if @review.save
			flash[:notice] = "Review submitted...."
			redirect_to @review.product
		else
			flash[:notice] = "Could not submit review...."
			render "new"
		end
	end

	def destroy
		@review = Review.find(params[:id])
		product = @review.product

		@review.destroy
		flash[:notice] = "Review deleted successfully..."
		redirect_to product
	end	

	private
		def review_params
			params.require(:review).permit(:user_id, :product_id, :star, :comment)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def avatar_url(user)
		gravatar = Digest::MD5.hexdigest(user.email)
			"https://www.gravatar.com/avatar/#{gravatar}.jpg?s=30"
	end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contacts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h2>Send your queries</h2>

			<%= form_for @contact do |f| %>

				<% if @contact.errors.any? %>
					<ul>
						<% @contact.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				
				<% end %>

				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :email %>
					<%= f.text_field :email, class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :body %>
					<%= f.text_area :body, class: "form-control" %>
				</div>

				<%= f.submit "Send Message", class: "btn btn-info" %>
			
			<% end %>
		</div>	
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sixerr4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<%= render "shared/header" %>
	</header>

	<body>
		<% flash.each do |name,msg| %>
			<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end %>

		<%= yield %>
	</body>

	<footer>
		
	</footer>

</body>
</html>

app/views/pages/home.html.erb
<div id="home_header">
	<div class="row" id="search-form">
		<div class="col-md-3">

		</div>
		<div class="col-md-6">
			<center>
				<span class="search-text">
					Hi, What you like to search today ?

					<%= form_tag search_path, method: :get do %>
						<div class="form-group center" style="color: black">
							<%= text_field_tag :q, nil, class: "form-control" %>
						</div>
						<%= submit_tag "Search", class: "btn btn-default" %>
					<% end %>

				</span>
			</center>
		</div>
		<div class="col-md-3">

		</div>
		
	</div>

</div>

app/views/pages/my_purchases.html.erb
<div class="container">
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Product Name</th>
				<th>Image</th>
				<th>Seller</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Total Price</th>
			</tr>
		</thead>
		<tbody>
			<% @purchases.each do |purchase| %>
				<tr>
					<td><%= purchase.product.name %></td>
					<td><%= image_tag purchase.product.image.url(:thumb) %></td>
					<td>
						<%= image_tag avatar_url(purchase.product.user) %>
					</td>
					<td><%= purchase.quantity %></td>
					<td><%= purchase.price %></td>
					<td><%= purchase.total_price %></td>
				</tr>
			<% end %>
		</tbody>

	</table>
</div>

app/views/pages/my_sales.html.erb
<h1>My Sales</h1>
<div class="container">
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Product Name</th>
				<th>Image</th>
				<th>Buyer</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Total Price</th>
			</tr>
		</thead>
		<tbody>
			<% @sales.each do |product| %>
				<tr>
					<td>
						<%= product.name %>
					</td>
					<td><%= image_tag product.image.url(:thumb) %></td>

					<% product.orders.each do |sale_product| %>
						<td> <%= image_tag avatar_url(sale_product.user) %></td>
						<td><%= sale_product.quantity %></td>
						<td><%= sale_product.price %></td>
						<td><%= sale_product.total_price %></td>
						</tr>
						<td></td>
						<td></td>
					<% end %>
			<% end %>
		</tbody>

	</table>
</div>

app/views/pages/search.html.erb
<div class="row">
	<div class="col-md-3">

	</div>
	<div class="col-md-6">
		<center>
			<span class="search-text" style="color:black">
				Hi, What you like to search today ?

				<%= form_tag search_path, method: :get do %>
					<div class="form-group center" style="color: black">
						<%= text_field_tag :q, nil, class: "form-control" %>
					</div>
					<%= submit_tag "Search", class: "btn btn-default" %>
				<% end %>

			</span>
		</center>
	</div>
	<div class="col-md-3">

	</div>
	
</div>

<div class="container">
	<div class="row">

		<%= render "products/products" %>
	</div>
</div>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
	
	<% if @product.errors.any? %>

		<% @product.errors.full_messages.each do |msg| %>
			<ul>
				<li><%= msg %></li>
			</ul>
		<% end %>
	
	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :price %>
		<%= f.text_field :price, class: "form-control" %>
	</div>

	<% if params[:action] == "edit" %>
		<%= f.submit "Update", class: "btn btn-primary" %>	
	<% else %>
		<%= f.submit "Save", class: "btn btn-primary" %>
	<% end %>

<% end %>

app/views/products/_products.html.erb
	<div class="row">
		<% @products.each_slice(3) do |products| %>
			<div class="row">
				<% products.each do |product| %>
					<div class="col-md-4">
						<div class="well">
							<% if product.image %>
								<%= image_tag product.image.url(:medium) %>
							<% end %>
							<h2><%= product.name %></h2>
							<p>
								<%= product.short_description %>
								<% if product.description.length > 130 %>
									<%= link_to "show more>>", product_path(product) %>
								<% end %>
							</p>
						</div>
						<hr>
						<%= link_to "Show", product_path(product), class: "btn btn-xs btn-info" %>
						<%= link_to "Edit", edit_product_path(product), class: "btn btn-xs btn-primary" %>
						<%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Sure to delete?"}, class: "btn btn-xs btn-danger" %>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<div class="container">
	<h1>Edit Product</h1>
	<hr>
	<%= render "form" %>

	<%= link_to "Back", products_path, class: "btn btn-default" %>
</div>

app/views/products/index.html.erb
<div class="container">
	<h1>All Products</h1>
	<hr>
	
	<%= will_paginate @products, renderer: BootstrapPagination::Rails %>
	
	<%= render "products" %>
	
	<%= will_paginate @products, renderer: BootstrapPagination::Rails %>
	
	<hr>

	<%= link_to "New Product", new_product_path, class: "btn btn-default" %>

</div>

app/views/products/my_products.html.erb
<div class="container">
	<h1>My Products</h1>
	<hr>
	
	<div class="row">
		<% @products.each do |product| %>
			<div class="col-md-4">
				<div class="well">
					<% if product.image %>
						<%= image_tag product.image.url(:medium) %>
					<% end %>
					<h2><%= product.name %></h2>
					<p><%= product.description %></p>
				</div>
				<hr>
				<%= link_to "Show", product_path(product), class: "btn btn-xs btn-info" %>
				<%= link_to "Edit", edit_product_path(product), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Sure to delete?"}, class: "btn btn-xs btn-danger" %>
			</div>
		<% end %>
	</div>

	<hr>

	<%= link_to "New Product", new_product_path, class: "btn btn-default" %>

</div>

app/views/products/new.html.erb
<div class="container">
	
	<h1>Product Entry</h1>
	<hr>

	<%= render "form" %>
</div>

app/views/products/show-no-stripe.html.erb
<div class="container">
	<div class="row">
		
		<div class="col-md-6">
			<div class="well">
				<%= image_tag @product.image.url(:medium) %>
				<hr>
				<h2><%= @product.price %></h2>
				<hr>
				<span class="label label-info">Description</span>
				<h3><%= @product.description %></h3>
			</div>
		</div>

		<div class="col-md-3">
			
		</div>

		<div class="col-md-3">
			<div class="well">
				<%= form_for([@product, @product.orders.new]) do |f| %>
					<%= f.hidden_field :product_id, value: @product.id %>
					<%= f.hidden_field :price, value: @product.price %>
					<center>
						<%= f.submit "Order Now - £#{@product.price}", class: "btn btn-info btn-lg btn-order" %>
					</center>
				
			</div>

			<hr>
			Select Quantity:
			<%= f.select :quantity, options_for_select([
					["1 (£#{@product.price * 1})", 1],
					["2 (£#{@product.price * 2})", 2],
					["3 (£#{@product.price * 3})", 3],
					["4 (£#{@product.price * 4})", 4],
					["5 (£#{@product.price * 5})", 5]
				]), {id: "quantity"} %>

			<% end %>

		</div>
	</div>
</div>

<script>
	$(document).ready(function(){
		$("select").bind("change", function(){
			$('.btn-order').val('Order Now -' + $("select option:selected").html());
		});
	})
</script>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		
		<div class="col-md-6">
			<div class="well">
				<%= image_tag @product.image.url(:medium) %>
				<hr>
				<h2><%= @product.price %></h2>
				<hr>
				<span class="label label-info">Description</span>
				<h3><%= @product.description %></h3>
			</div>
		</div>

		<div class="col-md-3">
			
		</div>

		<div class="col-md-3">
			<div class="well">
				<%= form_tag charges_path, id: 'chargeForm' do %>
				  <article>
				    <% if flash[:error].present? %>
				      <div id="error_explanation">
				        <p><%= flash[:error] %></p>
				      </div>
				    <% end %>
				  </article>

				  <script src="https://checkout.stripe.com/checkout.js"></script>
				  <%= hidden_field_tag 'stripeToken' %>
				  <%= hidden_field_tag 'stripeEmail' %>
				  <%= hidden_field_tag 'price', @product.price %>
				  <%= hidden_field_tag 'total_price', {id: "total_price"} %>
				  <%= hidden_field_tag 'product_id', @product.id %>
				  <%= hidden_field_tag 'description', @product.name %>
					
				  <center>
					<button type="button" id="btn-order" class="btn btn-primary btn-lg btn-order">
						Order Now ($<%= @product.price %>)
					</button>

					<script type="text/javascript">
						var handler = StripeCheckout.configure({
							key: '<%= Rails.configuration.stripe[:publishable_key] %>',
							token: function(token, arg) {
								document.getElementById("stripeToken").value = token.id;
								document.getElementById("stripeEmail").value = token.email;
								document.getElementById("chargeForm").submit();
							}
						});

						document.getElementById("btn-order").addEventListener('click', function(e){
							var quantity = $('#quantity').val();
							var total_price = (quantity * "<%= @product.price %>");
							var total_price = Math.round(total_price*100);
							$('#total_price').val(total_price);
							alert(total_price);
							handler.open({
								name: "Sixerr4",
								description: "<%= @product.name %>",
								amount: total_price
							});
							e.preventDefault();
						});
					</script>
							
				  </center>

			</div>

			<hr>
			Select Quantity:
			<%= select_tag :quantity, options_for_select([
					["1 (£#{@product.price.round(2) * 1})", 1],
					["2 (£#{@product.price * 2})", 2],
					["3 (£#{@product.price * 3})", 3],
					["4 (£#{@product.price * 4})", 4],
					["5 (£#{@product.price * 5})", 5]
				]), {id: "quantity"} %>

			<% end %>

		</div>
	</div>

	<div class="row">
		<h3>Reviews</h3>
		<hr>
		Review Average: <div id="review_average"></div>
		<hr>
		<% @reviews.each do |review| %>
			<div class="row well">
				<div class="col-md-2">

					<div id="review_star_<%= review.id %>"></div>
				</div>
				<div class="col-md-3">
					<%= image_tag avatar_url(review.user), class: "img-circle" %>
				</div>
				<div class="col-md-6"><%= review.comment %></div>
				<%= link_to "Delete", product_review_path(@product, review), method: :delete, data: {confirm: "Sure to Delete?"}, class: "btn btn-xs btn-danger" %>
			</div>

			<script>
				$('#review_star_<%= review.id %>').raty({
					path: '/assets',
					readOnly: true,
					scoreName: "review_<%= review.id %>",
					score: '<%= review.star %>'
				});
			</script>

		<% end %>
		
		<% if !@product.has_reviews(current_user) %>
			<%= render "reviews/form" %>		
		<% end %>

	</div>
	<br>
	<br>
	<br>
	<br>
</div>

<script>
	$(document).ready(function(){
		$("select").bind("change", function(){
			$('.btn-order').html('Order Now ' + $("select option:selected").html());
		});

		$('#review_average').raty({
			path: '/assets',
			scoreName: 'review_average',
			score: <%= @product.review_average %>,
			readOnly: true
		});
	})
</script>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/reviews/_form.html.erb
<%= form_for([@product, @product.reviews.new]) do |f|  %>
	
	<%= f.hidden_field :product_id, value: @product.id %>
	
	<div id="review_star_input"></div>

	<div class="form-group">
		<%= f.label :comment %>
		<%= f.text_area :comment, class: "form-control" %>
	</div>

	<%= f.submit "Submit Review", class: "btn btn-primary" %>

<% end %>


<script>
	$('#review_star_input').raty({
		path: '/assets',
		scoreName: 'review[star]',
		score: 1,
		readOnly: false
	});
</script>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Sixerr4", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><%= link_to "All Products", products_path %></li>
        <li><%= link_to "My Products", my_products_path %></li>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
              Order
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Sales", my_sales_path %></li>
              <li><%= link_to "Purchases", my_purchases_path %></li>
            </ul>
          </li>

      </ul>

      <%= link_to "Contact Us", new_contact_path, class: "btn navbar-btn btn-success"  %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
              <%= image_tag avatar_url(current_user), class: "img img-circle" %>
              <% if current_user.first_name || current_user.last_name %>
                <%= current_user.full_name %>
              <% else %>
                <%= current_user.email %>               
              <% end %>

              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: {confirm: "Sure to Sign Out"} %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>